/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangSustainabilityRouteImport } from './routes/$lang/sustainability'
import { Route as LangResourcesRouteImport } from './routes/$lang/resources'
import { Route as LangQualityRouteImport } from './routes/$lang/quality'
import { Route as LangIndustriesRouteImport } from './routes/$lang/industries'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products/index'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as LangProductsSlugRouteImport } from './routes/$lang/products/$slug'
import { Route as LangLegalPrivacyRouteImport } from './routes/$lang/legal/privacy'
import { Route as LangLegalNoticeRouteImport } from './routes/$lang/legal/notice'
import { Route as LangLegalCookiesRouteImport } from './routes/$lang/legal/cookies'
import { Route as LangCategoriesCategoryRouteImport } from './routes/$lang/categories/$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSustainabilityRoute = LangSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangResourcesRoute = LangResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangQualityRoute = LangQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangIndustriesRoute = LangIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalPrivacyRoute = LangLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalNoticeRoute = LangLegalNoticeRouteImport.update({
  id: '/legal/notice',
  path: '/legal/notice',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalCookiesRoute = LangLegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCategoriesCategoryRoute = LangCategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/quality': typeof LangQualityRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/sustainability': typeof LangSustainabilityRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/categories/$category': typeof LangCategoriesCategoryRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/notice': typeof LangLegalNoticeRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/quality': typeof LangQualityRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/sustainability': typeof LangSustainabilityRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/categories/$category': typeof LangCategoriesCategoryRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/notice': typeof LangLegalNoticeRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/$lang/products': typeof LangProductsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/industries': typeof LangIndustriesRoute
  '/$lang/quality': typeof LangQualityRoute
  '/$lang/resources': typeof LangResourcesRoute
  '/$lang/sustainability': typeof LangSustainabilityRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/categories/$category': typeof LangCategoriesCategoryRoute
  '/$lang/legal/cookies': typeof LangLegalCookiesRoute
  '/$lang/legal/notice': typeof LangLegalNoticeRoute
  '/$lang/legal/privacy': typeof LangLegalPrivacyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/auth'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/quality'
    | '/$lang/resources'
    | '/$lang/sustainability'
    | '/$lang/'
    | '/$lang/categories/$category'
    | '/$lang/legal/cookies'
    | '/$lang/legal/notice'
    | '/$lang/legal/privacy'
    | '/$lang/products/$slug'
    | '/admin/leads'
    | '/admin/products'
    | '/$lang/products/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/quality'
    | '/$lang/resources'
    | '/$lang/sustainability'
    | '/$lang'
    | '/$lang/categories/$category'
    | '/$lang/legal/cookies'
    | '/$lang/legal/notice'
    | '/$lang/legal/privacy'
    | '/$lang/products/$slug'
    | '/admin/leads'
    | '/admin/products'
    | '/$lang/products'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/industries'
    | '/$lang/quality'
    | '/$lang/resources'
    | '/$lang/sustainability'
    | '/$lang/'
    | '/$lang/categories/$category'
    | '/$lang/legal/cookies'
    | '/$lang/legal/notice'
    | '/$lang/legal/privacy'
    | '/$lang/products/$slug'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/products'
    | '/$lang/products/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/sustainability': {
      id: '/$lang/sustainability'
      path: '/sustainability'
      fullPath: '/$lang/sustainability'
      preLoaderRoute: typeof LangSustainabilityRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/resources': {
      id: '/$lang/resources'
      path: '/resources'
      fullPath: '/$lang/resources'
      preLoaderRoute: typeof LangResourcesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/quality': {
      id: '/$lang/quality'
      path: '/quality'
      fullPath: '/$lang/quality'
      preLoaderRoute: typeof LangQualityRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/industries': {
      id: '/$lang/industries'
      path: '/industries'
      fullPath: '/$lang/industries'
      preLoaderRoute: typeof LangIndustriesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/privacy': {
      id: '/$lang/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/$lang/legal/privacy'
      preLoaderRoute: typeof LangLegalPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/notice': {
      id: '/$lang/legal/notice'
      path: '/legal/notice'
      fullPath: '/$lang/legal/notice'
      preLoaderRoute: typeof LangLegalNoticeRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal/cookies': {
      id: '/$lang/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/$lang/legal/cookies'
      preLoaderRoute: typeof LangLegalCookiesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/categories/$category': {
      id: '/$lang/categories/$category'
      path: '/categories/$category'
      fullPath: '/$lang/categories/$category'
      preLoaderRoute: typeof LangCategoriesCategoryRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangIndustriesRoute: typeof LangIndustriesRoute
  LangQualityRoute: typeof LangQualityRoute
  LangResourcesRoute: typeof LangResourcesRoute
  LangSustainabilityRoute: typeof LangSustainabilityRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCategoriesCategoryRoute: typeof LangCategoriesCategoryRoute
  LangLegalCookiesRoute: typeof LangLegalCookiesRoute
  LangLegalNoticeRoute: typeof LangLegalNoticeRoute
  LangLegalPrivacyRoute: typeof LangLegalPrivacyRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangIndustriesRoute: LangIndustriesRoute,
  LangQualityRoute: LangQualityRoute,
  LangResourcesRoute: LangResourcesRoute,
  LangSustainabilityRoute: LangSustainabilityRoute,
  LangIndexRoute: LangIndexRoute,
  LangCategoriesCategoryRoute: LangCategoriesCategoryRoute,
  LangLegalCookiesRoute: LangLegalCookiesRoute,
  LangLegalNoticeRoute: LangLegalNoticeRoute,
  LangLegalPrivacyRoute: LangLegalPrivacyRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
